on: push
name: Build our patched harfbuzzjs
jobs:
  build-hbjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout harfbuzzjs
        uses: actions/checkout@v3
        with:
          repository: harfbuzz/harfbuzzjs
          path: harfbuzzjs
          submodules: recursive
          ref: emscripten
      - uses: mymindstorm/setup-emsdk@v11
      - name: Ugly patch
        run: cd harfbuzzjs/harfbuzz/ ; patch -p0 < ../../.github/harfbuzz-trace.patch
      - name: Build
        run: cd harfbuzzjs ; sh build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: harfbuzz.wasm
          path: harfbuzzjs/hb.wasm

